from app import app, db, CultureItem

def init_database():
    with app.app_context():
        db.create_all()
        CultureItem.query.delete()

        festivals = [
            {"name": "Diwali", "category": "festivals",
             "description": "The Festival of Lights, one of the most important Hindu festivals celebrating the victory of light over darkness. People light diyas, burst fireworks, and share sweets.",
             "location": "All India", "state": "Pan-India",
             "image_url": "https://images.unsplash.com/photo-1574015974293-817f0ebebb74?w=600&h=400&fit=crop"},
            {"name": "Holi", "category": "festivals",
             "description": "The Festival of Colors, celebrating the arrival of spring and the victory of good over evil. People play with colored powder and water, sing, and dance.",
             "location": "All India", "state": "Pan-India",
             "image_url": "https://images.unsplash.com/photo-1551009175-8a68da93d5f9?w=600&h=400&fit=crop"},
            {"name": "Pongal", "category": "festivals",
             "description": "A four-day harvest festival celebrated in Tamil Nadu, thanking the Sun God for a bountiful harvest. Features traditional foods, bull races, and decorative kolams.",
             "location": "Tamil Nadu", "state": "Tamil Nadu",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Pongal_decorated_kolam.jpg/800px-Pongal_decorated_kolam.jpg"},
            {"name": "Durga Puja", "category": "festivals",
             "description": "The most important festival of Bengal, celebrating the worship of Goddess Durga. Features elaborate pandals, cultural programs, and traditional feasts.",
             "location": "West Bengal", "state": "West Bengal",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Durga_Puja_Kolkata_2011_Sribhumi.jpg/800px-Durga_Puja_Kolkata_2011_Sribhumi.jpg"},
            {"name": "Navratri", "category": "festivals",
             "description": "A nine-night festival dedicated to Goddess Durga. Celebrated with fasting, Garba and Dandiya dancing, and religious ceremonies.",
             "location": "Gujarat, Maharashtra", "state": "Gujarat",
             "image_url": "https://images.unsplash.com/photo-1633178849004-3b4b1e6e21bf?w=600&h=400&fit=crop"},
            {"name": "Eid-ul-Fitr", "category": "festivals",
             "description": "An important Islamic festival marking the end of Ramadan. Muslims offer special prayers, share meals, and give to charity.",
             "location": "All India", "state": "Pan-India",
             "image_url": "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&h=400&fit=crop"},
            {"name": "Christmas", "category": "festivals",
             "description": "Celebrated by Christians across India, marking the birth of Jesus Christ. Features midnight mass, carols, decorations, and family gatherings.",
             "location": "All India", "state": "Pan-India",
             "image_url": "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=600&h=400&fit=crop"},
            {"name": "Onam", "category": "festivals",
             "description": "Kerala's harvest festival celebrating King Mahabali's homecoming. Features snake boat races, Kathakali performances, and the Onam Sadya feast.",
             "location": "Kerala", "state": "Kerala",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Onam_Pookalam.jpg/800px-Onam_Pookalam.jpg"},
        ]

        dance_forms = [
            {"name": "Bharatanatyam", "category": "dance_forms",
             "description": "One of the oldest classical dance forms of India, originating from Tamil Nadu. Known for its grace, sculpturesque poses, and expressive gestures.",
             "location": "Tamil Nadu", "state": "Tamil Nadu",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Bharatanatyam_Performance_DS.jpg/800px-Bharatanatyam_Performance_DS.jpg"},
            {"name": "Kathak", "category": "dance_forms",
             "description": "A classical dance from North India, known for intricate footwork, spins, and expressive storytelling. Influenced by both Hindu and Muslim cultures.",
             "location": "North India", "state": "Uttar Pradesh",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Kathak_dance_Lucknow_gharana.jpg/800px-Kathak_dance_Lucknow_gharana.jpg"},
            {"name": "Kathakali", "category": "dance_forms",
             "description": "A major classical dance from Kerala, known for elaborate costumes, makeup, and dramatic storytelling from Hindu epics like Mahabharata.",
             "location": "Kerala", "state": "Kerala",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Kathakaliperfomance.jpg/800px-Kathakaliperfomance.jpg"},
            {"name": "Odissi", "category": "dance_forms",
             "description": "A classical dance form from Odisha, known for lyrical movements and the tribhangi (three-bend) posture. One of the oldest surviving dance forms.",
             "location": "Odisha", "state": "Odisha",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Odissi_dance_in_Konark.jpg/800px-Odissi_dance_in_Konark.jpg"},
            {"name": "Manipuri", "category": "dance_forms",
             "description": "A classical dance form from Manipur, known for gentle, graceful movements and devotional themes depicting the love of Radha and Krishna.",
             "location": "Manipur", "state": "Manipur",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Manipuri_dance_performance.jpg/800px-Manipuri_dance_performance.jpg"},
            {"name": "Kuchipudi", "category": "dance_forms",
             "description": "A classical dance form from Andhra Pradesh, combining fast rhythms with graceful movements. Known for dramatic expressions and intricate footwork.",
             "location": "Andhra Pradesh", "state": "Andhra Pradesh",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Kuchipudi_DSC_1436.jpg/800px-Kuchipudi_DSC_1436.jpg"},
            {"name": "Mohiniyattam", "category": "dance_forms",
             "description": "A classical dance from Kerala known for graceful, feminine, swaying motions. The name means 'dance of the enchantress'.",
             "location": "Kerala", "state": "Kerala",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Mohiniyattam_2.jpg/800px-Mohiniyattam_2.jpg"},
            {"name": "Bhangra", "category": "dance_forms",
             "description": "A vibrant folk dance from Punjab, originally performed during the Baisakhi harvest festival. Known for energetic movements and upbeat music.",
             "location": "Punjab", "state": "Punjab",
             "image_url": "https://images.unsplash.com/photo-1545959570-a94084071b5d?w=600&h=400&fit=crop"},
        ]

        heritage_sites = [
            {"name": "Taj Mahal", "category": "heritage_sites",
             "description": "A UNESCO World Heritage Site and one of the Seven Wonders of the World. Built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal.",
             "location": "Agra", "state": "Uttar Pradesh",
             "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&h=400&fit=crop"},
            {"name": "Hampi", "category": "heritage_sites",
             "description": "A UNESCO World Heritage Site that was the capital of the Vijayanagara Empire. The ruins spread over 25 sq km include temples, palaces, and market streets.",
             "location": "Hampi", "state": "Karnataka",
             "image_url": "https://images.unsplash.com/photo-1600001491731-75fb3c9e1b97?w=600&h=400&fit=crop"},
            {"name": "Qutub Minar", "category": "heritage_sites",
             "description": "A UNESCO World Heritage Site — the world's tallest brick minaret at 73 metres. Built in the 12th century, it represents Indo-Islamic architecture.",
             "location": "Delhi", "state": "Delhi",
             "image_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&h=400&fit=crop"},
            {"name": "Ajanta Caves", "category": "heritage_sites",
             "description": "UNESCO World Heritage Site featuring rock-cut cave monuments with paintings and sculptures depicting Buddhist religious art from ancient India.",
             "location": "Aurangabad", "state": "Maharashtra",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Ajanta_cave9.jpg/800px-Ajanta_cave9.jpg"},
            {"name": "Khajuraho Temples", "category": "heritage_sites",
             "description": "A UNESCO World Heritage Site known for stunning architecture and intricate sculptures. Built between 950–1050 AD by the Chandela dynasty.",
             "location": "Khajuraho", "state": "Madhya Pradesh",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Kandariya_mahadeva_temple%2C_khajuraho.jpg/800px-Kandariya_mahadeva_temple%2C_khajuraho.jpg"},
            {"name": "Konark Sun Temple", "category": "heritage_sites",
             "description": "A UNESCO World Heritage Site shaped like a giant chariot. Dedicated to the Sun God, it represents the pinnacle of Kalinga architecture in Odisha.",
             "location": "Konark", "state": "Odisha",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Konarka_Temple.jpg/800px-Konarka_Temple.jpg"},
            {"name": "Red Fort", "category": "heritage_sites",
             "description": "A UNESCO World Heritage Site and symbol of India's independence. Built by Shah Jahan, it served as the main residence of the Mughal emperors.",
             "location": "Delhi", "state": "Delhi",
             "image_url": "https://images.unsplash.com/photo-1586183189334-f0a10e3e6c0f?w=600&h=400&fit=crop"},
            {"name": "Mahabalipuram", "category": "heritage_sites",
             "description": "A UNESCO World Heritage Site featuring rock-cut temples from the Pallava dynasty. Known for its Shore Temple and Five Rathas.",
             "location": "Mahabalipuram", "state": "Tamil Nadu",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Shore_Temple_Mahabalipuram_Tamil_Nadu_India.jpg/800px-Shore_Temple_Mahabalipuram_Tamil_Nadu_India.jpg"},
        ]

        cuisine = [
            {"name": "Biryani", "category": "cuisine",
             "description": "A fragrant rice dish made with basmati rice, spices, and meat or vegetables. Variations include Hyderabadi, Lucknowi, and Kolkata biryani.",
             "location": "All India", "state": "Pan-India",
             "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop"},
            {"name": "Masala Dosa", "category": "cuisine",
             "description": "A crispy crepe filled with spiced potato filling, a staple South Indian breakfast. Served with coconut chutney and sambar.",
             "location": "South India", "state": "Karnataka",
             "image_url": "https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&h=400&fit=crop"},
            {"name": "Butter Chicken", "category": "cuisine",
             "description": "A creamy tomato-based curry with tender chicken pieces, originating from Delhi. One of the most popular Indian dishes worldwide.",
             "location": "Delhi", "state": "Delhi",
             "image_url": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop"},
            {"name": "Rogan Josh", "category": "cuisine",
             "description": "An aromatic Kashmiri lamb curry made with yogurt and aromatic spices. The name means 'red juice' referring to its deep red color.",
             "location": "Kashmir", "state": "Jammu and Kashmir",
             "image_url": "https://images.unsplash.com/photo-1545247181-516773cae754?w=600&h=400&fit=crop"},
            {"name": "Dhokla", "category": "cuisine",
             "description": "A steamed savory cake made from fermented rice and chickpea batter, popular in Gujarat. Light, fluffy, and tempered with mustard seeds.",
             "location": "Gujarat", "state": "Gujarat",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Khaman_dhokla_%28dhokla%29.jpg/800px-Khaman_dhokla_%28dhokla%29.jpg"},
            {"name": "Chole Bhature", "category": "cuisine",
             "description": "A popular North Indian dish of spicy chickpea curry (chole) served with fried bread (bhature). A hearty breakfast or lunch option.",
             "location": "North India", "state": "Punjab",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Chole_bhature.jpg/800px-Chole_bhature.jpg"},
            {"name": "Samosa", "category": "cuisine",
             "description": "A crispy pastry filled with spiced potatoes, peas, and sometimes meat. One of India's most beloved snacks, served with chutneys.",
             "location": "All India", "state": "Pan-India",
             "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=400&fit=crop"},
            {"name": "Idli Sambar", "category": "cuisine",
             "description": "Soft steamed rice cakes served with lentil-based vegetable stew — a staple South Indian breakfast beloved across the country.",
             "location": "South India", "state": "Tamil Nadu",
             "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&h=400&fit=crop"},
        ]

        music = [
            {"name": "Hindustani Classical", "category": "music",
             "description": "North Indian classical music tradition, known for ragas and talas. Instruments include sitar, tabla, and sarod. Associated with legends like Ravi Shankar.",
             "location": "North India", "state": "Uttar Pradesh",
             "image_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&h=400&fit=crop"},
            {"name": "Carnatic Classical", "category": "music",
             "description": "South Indian classical music tradition emphasising vocal music and complex compositions. Instruments include veena, mridangam, and violin.",
             "location": "South India", "state": "Tamil Nadu",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Veena_shade.jpg/800px-Veena_shade.jpg"},
            {"name": "Bollywood Music", "category": "music",
             "description": "The music of Indian cinema, blending traditional Indian music with Western influences. Known for catchy melodies and romantic lyrics enjoyed worldwide.",
             "location": "Mumbai", "state": "Maharashtra",
             "image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop"},
            {"name": "Ghazal", "category": "music",
             "description": "A poetic form of music expressing love, loss, and beauty. Originating from Persian poetry, popular in Urdu and Hindi with maestros like Ghulam Ali.",
             "location": "North India", "state": "Delhi",
             "image_url": "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=600&h=400&fit=crop"},
            {"name": "Bhangra Music", "category": "music",
             "description": "Upbeat Punjabi folk music featuring energetic rhythms and instruments like the dhol. Popular at celebrations, weddings, and festivals.",
             "location": "Punjab", "state": "Punjab",
             "image_url": "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&h=400&fit=crop"},
            {"name": "Qawwali", "category": "music",
             "description": "Sufi devotional music known for its energetic, rhythmic style. Performed at shrines and religious ceremonies by artists like Nusrat Fateh Ali Khan.",
             "location": "North India", "state": "Uttar Pradesh",
             "image_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&h=400&fit=crop"},
            {"name": "Rabindra Sangeet", "category": "music",
             "description": "Songs composed by Nobel laureate Rabindranath Tagore, blending Indian classical with folk traditions. A cornerstone of Bengali cultural identity.",
             "location": "West Bengal", "state": "West Bengal",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Rabindranath_Tagore_in_1909.jpg/800px-Rabindranath_Tagore_in_1909.jpg"},
            {"name": "Folk Music of Rajasthan", "category": "music",
             "description": "Traditional Rajasthani folk music with instruments like the morchang, algoza, and sarangi. Songs tell stories of valor, love, and desert life.",
             "location": "Rajasthan", "state": "Rajasthan",
             "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&h=400&fit=crop"},
        ]

        art_forms = [
            {"name": "Madhubani Painting", "category": "art_forms",
             "description": "A traditional art form from Bihar characterized by geometric patterns and vibrant colors. Originally done on walls for festivals, now on canvas and paper.",
             "location": "Bihar", "state": "Bihar",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Madhubani_painting_by_Sarita_Devi_02.jpg/800px-Madhubani_painting_by_Sarita_Devi_02.jpg"},
            {"name": "Warli Art", "category": "art_forms",
             "description": "A tribal art from Maharashtra using basic geometric shapes — circles, triangles, squares — to depict daily life, nature, and celebrations.",
             "location": "Maharashtra", "state": "Maharashtra",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Warli_painting.jpg/800px-Warli_painting.jpg"},
            {"name": "Tanjore Painting", "category": "art_forms",
             "description": "A classical South Indian art from Thanjavur known for rich colors, gold foil work, and vibrant depictions of Hindu deities.",
             "location": "Tamil Nadu", "state": "Tamil Nadu",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Tanjore_painting_of_Lakshmi.jpg/800px-Tanjore_painting_of_Lakshmi.jpg"},
            {"name": "Pattachitra", "category": "art_forms",
             "description": "Traditional cloth-based scroll painting from Odisha and West Bengal, depicting mythological stories especially around Lord Jagannath.",
             "location": "Odisha", "state": "Odisha",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Pattachitra_Odisha.jpg/800px-Pattachitra_Odisha.jpg"},
            {"name": "Miniature Painting", "category": "art_forms",
             "description": "Detailed small-scale paintings developed in Mughal and Rajput courts. Known for intricate details, vibrant colors, and mythological themes.",
             "location": "Rajasthan", "state": "Rajasthan",
             "image_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=400&fit=crop"},
            {"name": "Kalamkari", "category": "art_forms",
             "description": "Hand-painted or block-printed cotton textile art from Andhra Pradesh, featuring mythological stories, floral motifs, and natural dyes.",
             "location": "Andhra Pradesh", "state": "Andhra Pradesh",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Kalamkari_textile_from_Andhra_Pradesh.jpg/800px-Kalamkari_textile_from_Andhra_Pradesh.jpg"},
            {"name": "Gond Art", "category": "art_forms",
             "description": "A tribal art form from Madhya Pradesh using dots and lines to create intricate patterns. Often depicts animals, birds, and nature in vivid colors.",
             "location": "Madhya Pradesh", "state": "Madhya Pradesh",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Gond_painting_of_fish.jpg/800px-Gond_painting_of_fish.jpg"},
            {"name": "Phulkari Embroidery", "category": "art_forms",
             "description": "Traditional embroidery from Punjab featuring vibrant floral patterns stitched in silk thread on cotton fabric. 'Phulkari' means 'flower work'.",
             "location": "Punjab", "state": "Punjab",
             "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop"},
        ]

        languages = [
            {"name": "Hindi", "category": "languages",
             "description": "The most widely spoken language in India, written in Devanagari script. One of the two official languages of the Union government with over 500 million speakers.",
             "location": "North and Central India", "state": "Multiple States",
             "image_url": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=400&fit=crop"},
            {"name": "Tamil", "category": "languages",
             "description": "One of the oldest living classical languages in the world, spoken in Tamil Nadu. Its literature spans over 2,000 years with the Sangam poems as its crowning glory.",
             "location": "Tamil Nadu", "state": "Tamil Nadu",
             "image_url": "https://images.unsplash.com/photo-1532153470116-e84643a7e6d3?w=600&h=400&fit=crop"},
            {"name": "Sanskrit", "category": "languages",
             "description": "The ancient scholarly language of India and liturgical language of Hinduism, Buddhism, and Jainism. The root of many modern Indian and European languages.",
             "location": "All India", "state": "Pan-India",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Rigveda_MS2097.jpg/800px-Rigveda_MS2097.jpg"},
            {"name": "Bengali", "category": "languages",
             "description": "The second most spoken language in India, with a rich literary tradition. Nobel laureate Rabindranath Tagore composed India's national anthem in Bengali.",
             "location": "West Bengal", "state": "West Bengal",
             "image_url": "https://images.unsplash.com/photo-1580894908361-967195033215?w=600&h=400&fit=crop"},
            {"name": "Telugu", "category": "languages",
             "description": "A Dravidian language spoken in Andhra Pradesh and Telangana with a classical status. Known as the 'Italian of the East' for its melodious sound.",
             "location": "Andhra Pradesh, Telangana", "state": "Andhra Pradesh",
             "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Telugu_Inscription_at_Hampi.jpg/800px-Telugu_Inscription_at_Hampi.jpg"},
            {"name": "Marathi", "category": "languages",
             "description": "The official language of Maharashtra with a literary tradition dating to the 13th century. Saint-poets like Tukaram and Dnyaneshwar wrote in Marathi.",
             "location": "Maharashtra", "state": "Maharashtra",
             "image_url": "https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=600&h=400&fit=crop"},
            {"name": "Gujarati", "category": "languages",
             "description": "The language of Gujarat, spoken by over 55 million people. Mahatma Gandhi's mother tongue, known for its rich mercantile and literary tradition.",
             "location": "Gujarat", "state": "Gujarat",
             "image_url": "https://images.unsplash.com/photo-1524069290683-0457abfe42c3?w=600&h=400&fit=crop"},
            {"name": "Malayalam", "category": "languages",
             "description": "A Dravidian language of Kerala known for its palindromic script and high literacy rate. Kerala's education system, built on this language, is a national model.",
             "location": "Kerala", "state": "Kerala",
             "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&h=400&fit=crop"},
        ]

        all_items = festivals + dance_forms + heritage_sites + cuisine + music + art_forms + languages
        for item_data in all_items:
            db.session.add(CultureItem(**item_data))
        db.session.commit()
        print(f"Successfully added {len(all_items)} items to the database!")

if __name__ == '__main__':
    init_database()
